// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import favicon from "@/assets/images/svg/enrilo-e-transparent-bg.svg";

export const metadata = {
  title: "Enrilo",
  description: "Enrilo is a consultancy management platform that helps teams manage students, track visa applications, handle payments, and streamline operations all in one place.",
  icons: {
    icon: favicon.src,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

// import "./globals.css";
// import Header from "@/components/Header";
// import Footer from "@/components/Footer";

// export const metadata = {
//   title: "Enrilo",
//   description: "Enrilo is a consultancy management platform that helps teams manage students, track visa applications, handle payments, and streamline operations all in one place.",
//   icons: {
//     icon: '/src/assets/images/svg/enrilo-e-transparent-bg.svg',
//     // shortcut: '/logo.png',
//     // apple: '/apple-icon.png',
//   },
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head>
//         <meta charSet="UTF-8" />
//         <link rel="icon" type="image/svg+xml" href="/src/assets/images/svg/enrilo-e-transparent-bg.svg" />
//         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
//         <title>Enrilo</title>
//       </head>
//       <body>
//         <Header />
//         {children}
//         {/* <div style={{ display: "flex" }}>
//           {children}
//         </div> */}
//         <Footer />
//       </body>
//     </html>
//   );
// }